name: GitHub Page PR Preview Deploy

on:
  pull_request:
    types: [labeled]

jobs:
  firebase-pr-preview:
    name: GitHub Pages PR Deploy
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'create-live-preview')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Setup Node v14
        uses: actions/setup-node@master
        with:
          node-version: "14.x"

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: cd client && yarn install --frozen-lockfile

      - name: Build React WebApp
        run: cd client && yarn build

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Deploy to GitHub Page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/build
          publish_branch: ${{ steps.extract_branch.outputs.branch }}

      - name: removelabel
        uses: buildsville/add-remove-label@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          deploy_key: ${{secrets.ACTIONS_DEPLOY_KEY}}
          label: create-live-preview
          type: remove
